Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', to: 'bitcoin_app#index'
  get '/index', to: 'bitcoin_app#index'
  get '/index/:blockheight/:blocknum', to: 'bitcoin_app#index', as: 'pagenation'
  get '/tx/:txid', to: 'bitcoin_app#txinfo', as: 'txinfo'
  get '/block/:blockhash', to: 'bitcoin_app#blockinfo', as: 'blockinfo'
  get '/blockheight/:blockheight', to: 'bitcoin_app#blockheightinfo', as: 'blockheightinfo'
  get '/address/:address', to: 'bitcoin_app#addressinfo', as: 'addressinfo'
  get '/mining', to: 'bitcoin_app#mining'
  post '/mine', to: 'bitcoin_app#mine'
  get '/mine', to: 'bitcoin_app#mine'
  get '/sendings', to: 'bitcoin_app#sendings'
  post '/sent', to: 'bitcoin_app#sent'
  get '/search', to: 'bitcoin_app#search'
  get '/notfound', to: 'bitcoin_app#notfound'
  get '/receive', to: 'bitcoin_app#receive'
  post '/receive', to: 'bitcoin_app#receive'
  get '/addresslist', to: 'bitcoin_app#addresslist'
  get '/txlist', to: 'bitcoin_app#txlist'
  get '/wallet', to: 'bitcoin_app#wallet'
  get '/utxolist', to: 'bitcoin_app#utxolist'
  get '/utxolist/:oaaddress', to: 'bitcoin_app#utxolist', as: 'utxo_oaaddress'
  get '/assetutxo', to: 'bitcoin_app#assetutxo', as: 'assetutxo'
  post '/assetissue', to: 'bitcoin_app#assetissue', as: 'assetissue'
  get 'lightning', to: 'lightning#lightning', as: 'lightning_index'
  get 'lightning/:message', to: 'lightning#lightning', as: 'lightning'
  get 'lightning_pay', to: 'lightning#pay', as: 'pay'
  post 'lightning_paid', to: 'lightning#paid'
  get 'lightning_listsendpays', to: 'lightning#listsendpays', as: 'listsendpays'
  get 'lightning_issue_invoice', to: 'lightning#issue_invoice', as: 'issue_invoice'
  post 'lightning_invoice', to: 'lightning#invoice', as: 'invoice'
  get 'lightning_listinvoices', to: 'lightning#listinvoices', as: 'listinvoices'
  post 'lightning_ping', to: 'lightning#ping', as: 'ping'
  post 'lightning_connect', to: 'lightning#connect', as: 'connect'
  post 'lightning_fundchannel', to: 'lightning#fundchannel', as: 'fundchannel'
  get 'lightning_deposit', to: 'lightning#deposit'
  post 'lightning_deposit', to: 'lightning#deposit'
  post 'lightning_close', to: 'lightning#close', as: 'close'
  post 'lightning_withdraw', to: 'lightning#withdraw', as: 'withdraw'
  get 'lightning_listchannels', to: 'lightning#listchannels', as: 'listchannels'
  get 'lightning_shop', to: 'lightning#shop', as: 'lightning_shop'
end
